### ISSUE TITLE
访问概览打开报错

### ISSUE THREAD

**Issue by JustForRain** [kokororin/typecho-plugin-Access#14]
typecho 17.8.17
php 7.1.8
typecho使用pdo链接数据库
打开插件访问概览报如下错误，请问我该怎么修改sql查询语句？
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Typecho_Db_Query_Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/typecho/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/html/typecho/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('SELECT COUNT(1)...', Object(PDO), 1, 'SELECT')
#1 /var/www/html/typecho/var/Typecho/Db.php(384): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /var/www/html/typecho/usr/plugins/Access/Access_Core.php(183): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /var/www/html/typecho/usr/plugins/Access/Access_Core.php(47): Access_Core->parseOverview()
#4 /var/www/html/typecho/usr/plugins/Access/page/console.php(6): Access_Core->__construct()
#5 /var/www/html/typecho/admin/extending.php(13): require_once('/var/www/html/t...')
#6 {main}
```

**Comment by kokororin** [comment]
fixed
